pipeline {
  agent any

  environment {
    AWS_ACCESS_KEY_ID = credentials('aws-access-key')
    AWS_SECRET_ACCESS_KEY = credentials('aws-secret-key')
  }

  stages {
    stage('Checkout') {
      steps {
        git url: 'https://github.com/Bharathicloud/wordpress-ami-project.git', branch: 'main'
      }
    }

    stage('Packer Build') {
  steps {
    dir('packer') {
      sh 'packer init .'
      sh 'packer validate wordpress-ami.pkr.hcl'
      sh 'packer build wordpress-ami.pkr.hcl'
        }
      }
    }
  }
}
