- hosts: all
  become: true
  tasks:
    - name: Install Apache, PHP, and dependencies
      apt:
        name:
          - apache2
          - php
          - php-mysql
          - libapache2-mod-php
          - mysql-client
        state: present
        update_cache: yes

    - name: Download latest WordPress
      get_url:
        url: https://wordpress.org/latest.tar.gz
        dest: /tmp/wordpress.tar.gz

    - name: Extract WordPress
      unarchive:
        src: /tmp/wordpress.tar.gz
        dest: /var/www/html/
        remote_src: yes

    - name: Set permissions
      file:
        path: /var/www/html/wordpress
        owner: www-data
        group: www-data
        recurse: yes

    - name: Configure wp-config.php
      template:
        src: wp-config.php.j2
        dest: /var/www/html/wordpress/wp-config.php
